version: '3.7'
services:
  tasks-demo-frontend:
    environment: 
      - REACT_APP_API_PORT=8080
      - REACT_APP_API_SERVER=localhost
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ambatlle/tasks-app-frontend:latest
    networks:
      tasks-demo-net:
    ports:
      - 80:3000
    volumes:
      - node_modules_frontend:/root/dev/myapp/node_modules
    depends_on:
      - tasks-demo-backend

  tasks-demo-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ambatlle/tasks-app-backend:latest
    networks:
      tasks-demo-net:
    ports:
      - 8080:8080
      - 8081:8081

volumes:
  #used to cache the node_modules to improve building time
  node_modules_frontend:

networks:
  tasks-demo-net:
