version: '3.7'
services:
  tasks-demo-frontend:
    env_file: .env.local
    #env_file: .env.server
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ambatlle/tasks-app-frontend:latest
    networks:
      tasks-demo-net:
    ports:
      - 80:3000
    depends_on:
      - tasks-demo-backend

  tasks-demo-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ambatlle/tasks-app-backend:latest
    networks:
      tasks-demo-net:
    ports:
      - 8080:8080
      - 8081:8081

networks:
  tasks-demo-net:
